// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyttzvpmxldswvtalott.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dHR6dnBteGxkc3d2dGFsb3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzI2OTAsImV4cCI6MjA1OTYwODY5MH0.D_4nnSPUCiNtW4bRDmB5zWrDZqLUfgZnuul5_ILjLYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);